version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check for npm updates on Sundays at 7pm EST
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/"
    # Check for npm updates on Wednesdays at 7pm EST
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "23:00"
    target-branch: "develop"

    