/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconConfig } from "./components/icon/djl-icon";
export namespace Components {
    interface DjlButton {
        /**
          * (optional) aria-label for <button> element
         */
        "ariaLabelBtn"?: string;
        /**
          * (optional) Category for <button> custom element
         */
        "category"?: 'primary' | 'secondary' | 'plain';
        /**
          * (optional) Color attribute for <button> element
         */
        "color"?: 'critical' | 'CTA';
        /**
          * (optional) Disabled attribute for <button> element
         */
        "disabled"?: boolean;
        /**
          * (optional) Name attribute for <button> element
         */
        "name"?: string;
        /**
          * (optional) Size for <button> custom element
         */
        "size"?: 'small' | 'large';
        /**
          * (optional) Types for <button> element
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * (optional)  Value for <button> element
         */
        "value"?: string;
    }
    interface DjlIcon {
        /**
          * Icon config json object, or parsable json string
          * @example ``` {    unicode : 'f6b0',    fontFamily : 'fa-solid' } ```
          * @example ``` '{"unicode": "f6b0", "fontFamily": "fa-solid"}' ```
         */
        "iconConfig": IconConfig | string;
    }
    interface DjlLink {
        "ariaLabel": string;
        /**
          * If developer is specifying a download in the href, they need to specify a download name in order for the "download icon" to appear next to it
         */
        "download"?: string;
        "href": string;
        "target"?: '_blank' | '_parent' | '_self' | '_top';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * Theme
         */
        "theme": string;
    }
}
declare global {
    interface HTMLDjlButtonElement extends Components.DjlButton, HTMLStencilElement {
    }
    var HTMLDjlButtonElement: {
        prototype: HTMLDjlButtonElement;
        new (): HTMLDjlButtonElement;
    };
    interface HTMLDjlIconElement extends Components.DjlIcon, HTMLStencilElement {
    }
    var HTMLDjlIconElement: {
        prototype: HTMLDjlIconElement;
        new (): HTMLDjlIconElement;
    };
    interface HTMLDjlLinkElement extends Components.DjlLink, HTMLStencilElement {
    }
    var HTMLDjlLinkElement: {
        prototype: HTMLDjlLinkElement;
        new (): HTMLDjlLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "djl-button": HTMLDjlButtonElement;
        "djl-icon": HTMLDjlIconElement;
        "djl-link": HTMLDjlLinkElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DjlButton {
        /**
          * (optional) aria-label for <button> element
         */
        "ariaLabelBtn"?: string;
        /**
          * (optional) Category for <button> custom element
         */
        "category"?: 'primary' | 'secondary' | 'plain';
        /**
          * (optional) Color attribute for <button> element
         */
        "color"?: 'critical' | 'CTA';
        /**
          * (optional) Disabled attribute for <button> element
         */
        "disabled"?: boolean;
        /**
          * (optional) Name attribute for <button> element
         */
        "name"?: string;
        /**
          * (optional) Size for <button> custom element
         */
        "size"?: 'small' | 'large';
        /**
          * (optional) Types for <button> element
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * (optional)  Value for <button> element
         */
        "value"?: string;
    }
    interface DjlIcon {
        /**
          * Icon config json object, or parsable json string
          * @example ``` {    unicode : 'f6b0',    fontFamily : 'fa-solid' } ```
          * @example ``` '{"unicode": "f6b0", "fontFamily": "fa-solid"}' ```
         */
        "iconConfig"?: IconConfig | string;
    }
    interface DjlLink {
        "ariaLabel"?: string;
        /**
          * If developer is specifying a download in the href, they need to specify a download name in order for the "download icon" to appear next to it
         */
        "download"?: string;
        "href": string;
        "target"?: '_blank' | '_parent' | '_self' | '_top';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * Theme
         */
        "theme"?: string;
    }
    interface IntrinsicElements {
        "djl-button": DjlButton;
        "djl-icon": DjlIcon;
        "djl-link": DjlLink;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "djl-button": LocalJSX.DjlButton & JSXBase.HTMLAttributes<HTMLDjlButtonElement>;
            "djl-icon": LocalJSX.DjlIcon & JSXBase.HTMLAttributes<HTMLDjlIconElement>;
            "djl-link": LocalJSX.DjlLink & JSXBase.HTMLAttributes<HTMLDjlLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
