/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DjlButton {
        /**
          * (optional) aria-label for <button> element
         */
        "ariaLabelBtn"?: string;
        /**
          * (optional) Category for <button> custom element
         */
        "category"?: 'primary' | 'secondary' | 'plain';
        /**
          * (optional) Color attribute for <button> element
         */
        "color"?: 'critical' | 'CTA';
        /**
          * (optional) Disabled attribute for <button> element
         */
        "disabled"?: boolean;
        /**
          * (optional) Name attribute for <button> element
         */
        "name"?: string;
        /**
          * (optional) Size for <button> custom element
         */
        "size"?: 'small' | 'large';
        /**
          * (optional) Types for <button> element
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * (optional)  Value for <button> element
         */
        "value"?: string;
    }
    interface DjlLink {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * Theme
         */
        "theme": string;
    }
}
declare global {
    interface HTMLDjlButtonElement extends Components.DjlButton, HTMLStencilElement {
    }
    var HTMLDjlButtonElement: {
        prototype: HTMLDjlButtonElement;
        new (): HTMLDjlButtonElement;
    };
    interface HTMLDjlLinkElement extends Components.DjlLink, HTMLStencilElement {
    }
    var HTMLDjlLinkElement: {
        prototype: HTMLDjlLinkElement;
        new (): HTMLDjlLinkElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "djl-button": HTMLDjlButtonElement;
        "djl-link": HTMLDjlLinkElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DjlButton {
        /**
          * (optional) aria-label for <button> element
         */
        "ariaLabelBtn"?: string;
        /**
          * (optional) Category for <button> custom element
         */
        "category"?: 'primary' | 'secondary' | 'plain';
        /**
          * (optional) Color attribute for <button> element
         */
        "color"?: 'critical' | 'CTA';
        /**
          * (optional) Disabled attribute for <button> element
         */
        "disabled"?: boolean;
        /**
          * (optional) Name attribute for <button> element
         */
        "name"?: string;
        /**
          * (optional) Size for <button> custom element
         */
        "size"?: 'small' | 'large';
        /**
          * (optional) Types for <button> element
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * (optional)  Value for <button> element
         */
        "value"?: string;
    }
    interface DjlLink {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * Theme
         */
        "theme"?: string;
    }
    interface IntrinsicElements {
        "djl-button": DjlButton;
        "djl-link": DjlLink;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "djl-button": LocalJSX.DjlButton & JSXBase.HTMLAttributes<HTMLDjlButtonElement>;
            "djl-link": LocalJSX.DjlLink & JSXBase.HTMLAttributes<HTMLDjlLinkElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
