name: Checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout all branches and tags
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with: 
        node-version: '16'
    - name: "Setup npm"
      run: | # Set registry and authenticate with repo token
        npm set @ircc-ca:registry=https://registry.npmjs.com/
        npm set "//registry.npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}"
    - name: Install dependencies
      run: | # Install and link dependencies
        npx lerna bootstrap
    - name: Run tests # Run tests and linting for all packages
      run: |
        # npx lerna run test
        npx lerna run lint