name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main
  workflow_dispatch:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout all branches and tags
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with: 
        node-version: '16'
    - name: "Version and publish"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        echo PRE-BOOTSTRAP
        npx lerna bootstrap
        echo POST-BOOTSTRAP
        echo GIT REF:    ${{ github.ref }}
        if [ ${{ github.ref }} == 'main' ]; then
          echo ECHO message: branch is MAIN
          npx lerna version --conventional-commits --conventional-graduate --yes
        else
          echo ECHO message: branch is NOT MAIN
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        fi
        npx lerna run build --scope=@ircc-ca/ds-sdc-core
        echo core package built
        npx lerna run build --scope=@ircc-ca/ds-sdc-web
        echo web package built
        npx lerna run build --scope=@ircc-ca/ds-sdc-angular
        echo angular package built
        npx lerna run build --scope=@ircc-ca/ds-sdc-react
        echo react package built
        npm publish --access=public
