name: Publish Storybook
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout all branches and tags
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with: 
        node-version: '16'
    - name: "Setup npm"
      run: | # Set registry and authenticate with repo token
        npm set @ircc-ca:registry=https://npm.pkg.github.com/ircc-ca
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
        npm set @fortawesome:registry=https://npm.fontawesome.com/
        npm set "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
    - name: "Install dependencies"
      run: | # Install and link dependencies
        npx lerna bootstrap
    - name: "Build packages"
      run: npm run build:packages
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ca-central-1'
    - name: "Create storybook static folder"
      run: npm run storybook:build
    - name: "Push storybook static to S3"
      run: aws s3 sync ./ ${{ secrets.AWS_BUCKET_SB }}

